name: .NET Core Test & Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      Solution_Name: TerminalSolitaire.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ env.Solution_Name }}

    - name: Restore Dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build Solution
      run: dotnet build $env:Solution_Name --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test $env:Test_Project_Path --configuration Release --no-build --verbosity normal