name: .NET Core Test, Build, & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-dotnet:
    runs-on: windows-latest

    env:
      Solution_Name: local-app/TerminalSolitaire.sln
      Project_Path: local-app/TerminalSolitaire.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    
    - name: Debug - List Files
      run: ls -R
      
    - name: Restore Dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build Solution
      run: dotnet build ${{ env.Solution_Name }} --configuration Debug --no-restore
      
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ env.Solution_Name }} --configuration Debug --no-build
      
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Dependencies
        run: bundle install --without development test

      - name: Run Tests
        run: bundle exec rspec
   
   
   deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        #run: |
        #  mkdir -p ~/.ssh
        # echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        #  chmod 600 ~/.ssh/id_rsa
         # ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        #run: |
        #  ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
         #   set -e
         #   cd ~/highscores-api || git clone https://github.com/Team9NCI/Project-2025.git ~/highscores-api
         #   cd ~/highscores-api
         #   git pull origin main
         #   bundle install --without development test
         #   RAILS_ENV=production rails db:migrate
          #  sudo systemctl restart highscores
        #  EOF
   