name: Ruby Rails Test, Build, & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Dependencies
        run: bundle install --without development test

      - name: Run Tests
        run: bundle exec rspec
   
   
  deploy:
    needs: build-and-test-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/github_actions_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Get the api folder
            cd /home/ubuntu/devopsec-project-2025/highscores-api || { echo "Failed to change directory"; exit 1; }
            
            # Remove 2025/local-app if it exists
            rm -rf /home/ubuntu/devopsec-project-2025/2025/local-app
            # Debug: Confirm deletion
            if [ -d "/home/ubuntu/devopsec-project-2025/2025/local-app" ]; then
                echo "❌ Failed to delete 2025/local-app"
                exit 1
            else
                echo "✅ Successfully deleted 2025/local-app"
            fi
            
            # Ensure Git pulls the latest changes
            git pull origin main
            
            # Ensure the correct Ruby version is used
            rbenv local 3.2.0 || echo "Warning: rbenv not set up correctly"
            bundle config set --local without 'development test'
            bundle install
            rails db:migrate
            
            # Restart the server
            sudo systemctl restart highscores-api
          EOF
   