name: Ruby Rails Test, Build, & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          
      - name: Run Tests
        run: |
          cd highscores-api || { echo "directory 'highscores-api' not found!"; exit 1; }
          bundle install
          bundle exec rspec
   
  deploy:
    needs: build-and-test-server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_actions_key
            chmod 600 ~/.ssh/github_actions_key
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          ssh -i ~/.ssh/github_actions_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
            # using set +e to continue even if some commands fail
            set +e
            
            # setup app directory
            mkdir -p ~/app
            cd ~/app
            
            # ensure the repository exists, or clone it
            if [ -d "Project-2025" ]; then
              cd Project-2025
              git fetch
              git reset --hard origin/main
            else
              git clone https://github.com/Team9NCI/Project-2025.git
              cd Project-2025
            fi
            
            # navigate to the highscores-api directory
            cd highscores-api
            echo "current directory: $(pwd)"
            
            # install comprehensive system dependencies
            echo "installing system dependencies..."
            sudo apt update -y
            sudo apt install -y build-essential git curl libssl-dev libreadline-dev 
            sudo apt install -y zlib1g-dev sqlite3 libsqlite3-dev 
            sudo apt install -y autoconf bison libyaml-dev libgdbm-dev libncurses5-dev automake libtool
            sudo apt install -y libffi-dev nodejs npm libxml2-dev libxslt1-dev
            
            # install rvm for better ruby environment management
            echo "installing rvm and ruby..."
            if ! command -v rvm &> /dev/null; then
              curl -sSL https://get.rvm.io | bash -s stable
              source ~/.rvm/scripts/rvm
              rvm install 3.2
              rvm use 3.2 --default
            fi
            
            # check ruby installation
            source ~/.rvm/scripts/rvm
            rvm use 3.2
            ruby -v
            
            # set the master key
            echo "setting up master key..."
            echo "${RAILS_MASTER_KEY}" > config/master.key
            chmod 600 config/master.key
            
            # create needed directories
            mkdir -p db storage log tmp/pids
            
            # set permissions
            chmod -R 755 .
            
            # install gems with rvm ruby
            echo "installing project dependencies..."
            gem install bundler
            bundle install
            
            # run migrations
            echo "running database migrations..."
            RAILS_ENV=production bundle exec rails db:migrate || echo "migration failed but continuing"
            
            # create systemd service file
            echo "creating systemd service file..."
            sudo rm -f /etc/systemd/system/highscores-api.service
            cat << EOF | sudo tee /etc/systemd/system/highscores-api.service > /dev/null
[Unit]
Description=Highscores Rails API
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$PWD
ExecStart=/bin/bash -l -c 'source ~/.rvm/scripts/rvm && bundle exec rails server -e production -p 3000 -b 0.0.0.0'
Restart=on-failure
Environment=RAILS_ENV=production
Environment=RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
Environment=RAILS_SERVE_STATIC_FILES=true
StandardOutput=append:/var/log/highscores-api.log
StandardError=append:/var/log/highscores-api.error.log

[Install]
WantedBy=multi-user.target
EOF
            
            # create log files with proper permissions
            sudo touch /var/log/highscores-api.log
            sudo touch /var/log/highscores-api.error.log
            sudo chown $USER:$USER /var/log/highscores-api.*
            
            # setup nginx
            echo "setting up nginx..."
            sudo apt install -y nginx
            
            # create nginx config
            cat << EOF | sudo tee /etc/nginx/sites-available/highscores-api > /dev/null
server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
            
            sudo ln -sf /etc/nginx/sites-available/highscores-api /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo systemctl restart nginx
            
            # reload systemd
            echo "reloading systemd..."
            sudo systemctl daemon-reload
            
            # enable and start the service
            echo "enabling service..."
            sudo systemctl enable highscores-api
            
            echo "starting service..."
            sudo systemctl restart highscores-api
            sleep 5
            sudo systemctl status highscores-api || true
            
            # if service fails, try direct start
            if ! sudo systemctl is-active --quiet highscores-api; then
              echo "service failed to start, trying manual start..."
              cd $PWD
              source ~/.rvm/scripts/rvm
              rvm use 3.2
              RAILS_ENV=production RAILS_MASTER_KEY=${RAILS_MASTER_KEY} nohup bundle exec rails server -p 3000 -b 0.0.0.0 > ~/rails.log 2>&1 &
              echo "server started in background"
            fi
            
            echo "deployment process completed"
          ENDSSH