name: Ruby Rails Test, Build, & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          
      - name: Debug current directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in the current directory:"
          ls -l
          
      - name: Navigate to server folder & Install Dependencies
        run: |
          cd highscores-api || { echo "Directory 'highscores-api' not found!"; exit 1; }
          
          echo "Current directory after cd: $(pwd)"
          
          if [ -f "Gemfile" ]; then
            echo "Gemfile found"
          else
            echo "Gemfile not found!"
            exit 1
          fi
          bundle install
          
          # Debug: Check if rspec is available
          bundle exec rspec --version || { echo "rspec is not installed"; exit 1; }

          echo "Executing"
          bundle exec rspec
   
   
  deploy:
    needs: build-and-test-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_actions_key
            chmod 600 ~/.ssh/github_actions_key
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Configure SSH for Git
        run: |
            echo "Host github.com" >> ~/.ssh/config
            echo "  IdentityFile ~/.ssh/github_actions_key" >> ~/.ssh/config
            echo "  IdentitiesOnly yes" >> ~/.ssh/config
            
      - name: Test SSH Connection
        run: |
           ssh -T git@github.com || true

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/github_actions_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~
            
            # Ensure the repository exists, or clone it
            if [ ! -d "devopsec-project-2025" ]; then
              git clone https://github.com/Team9NCI/Project-2025.git devopsec-project-2025
            fi
            
            cd devopsec-project-2025

            # Ensure Git pulls the latest changes
            git reset --hard origin/main
            git pull origin main
            
            # Navigate to the highscores-api directory
            cd highscores-api || { echo "Failed to access highscores-api"; exit 1; }
            # Debug current directory
            echo "Current directory: $(pwd)"
            ls -l
            
            # Ensure the correct Ruby version is used
            rbenv install 3.2.0
            rbenv local 3.2.0 || echo "rbenv not set up correctly"
            bundle config set without 'development test'
            bundle install
            
            # Run the migrations
            rails db:migrate
            
            # Restart the server
            sudo systemctl restart highscores-api
          EOF
   